/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travel;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ravisharma
 */
public class FinalBooking extends javax.swing.JFrame {

    ResultSet rs;
    int op;
    Vector v1;
    double totalfare;
    /**
     * Creates new form FinalBooking
     */
    public FinalBooking() {
        initComponents();
        Color backgroundcolor = new Color(0,0,0); 
        this.getContentPane().setBackground(backgroundcolor);
        returnjpanel.setVisible(false); 
        setVisible(true); 
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnjpanel = new javax.swing.JPanel();
        lblreturnflight = new javax.swing.JLabel();
        lblreturnflightcode = new javax.swing.JLabel();
        lblreturndate = new javax.swing.JLabel();
        lblreturntime = new javax.swing.JLabel();
        lblreturnfare = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbsalutation = new javax.swing.JComboBox<>();
        txtfirst = new javax.swing.JTextField();
        txtlast = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        lbltotalfare = new javax.swing.JLabel();
        buttonconfirm = new javax.swing.JButton();
        departjpanel = new javax.swing.JPanel();
        lbldepartflight1 = new javax.swing.JLabel();
        lbldepartflightcode1 = new javax.swing.JLabel();
        lbldepartdate1 = new javax.swing.JLabel();
        lbldeparttime1 = new javax.swing.JLabel();
        lbldepartfare1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        lblreturnflight.setText("jLabel7");

        lblreturnflightcode.setText("FLIGHT CODE : ");

        lblreturndate.setText("RETURN DATE : ");

        lblreturntime.setText("RETURN TIME :");

        lblreturnfare.setText("FARE : ");

        javax.swing.GroupLayout returnjpanelLayout = new javax.swing.GroupLayout(returnjpanel);
        returnjpanel.setLayout(returnjpanelLayout);
        returnjpanelLayout.setHorizontalGroup(
            returnjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnjpanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(returnjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblreturnfare)
                    .addComponent(lblreturnflightcode)
                    .addComponent(lblreturnflight)
                    .addComponent(lblreturndate)
                    .addComponent(lblreturntime))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        returnjpanelLayout.setVerticalGroup(
            returnjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnjpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblreturnflight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(lblreturnflightcode)
                .addGap(27, 27, 27)
                .addComponent(lblreturndate)
                .addGap(26, 26, 26)
                .addComponent(lblreturntime)
                .addGap(18, 18, 18)
                .addComponent(lblreturnfare)
                .addGap(26, 26, 26))
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Complete Your Booking");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Salutation");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact No.");

        cmbsalutation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Ms.", "Mrs." }));

        txtfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstActionPerformed(evt);
            }
        });

        lbltotalfare.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalfare.setText("Total Fare (Including 5% GST) : ");

        buttonconfirm.setText("CONFIRM BOOKING");
        buttonconfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonconfirmMouseClicked(evt);
            }
        });
        buttonconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonconfirmActionPerformed(evt);
            }
        });

        lbldepartflight1.setText("jLabel7");

        lbldepartflightcode1.setText("FLIGHT CODE : ");

        lbldepartdate1.setText("DEPARTURE DATE : ");

        lbldeparttime1.setText("DEPARTURE TIME :");

        lbldepartfare1.setText("FARE : ");

        javax.swing.GroupLayout departjpanelLayout = new javax.swing.GroupLayout(departjpanel);
        departjpanel.setLayout(departjpanelLayout);
        departjpanelLayout.setHorizontalGroup(
            departjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departjpanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(departjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldepartfare1)
                    .addComponent(lbldepartflightcode1)
                    .addComponent(lbldepartflight1)
                    .addComponent(lbldepartdate1)
                    .addComponent(lbldeparttime1))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        departjpanelLayout.setVerticalGroup(
            departjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departjpanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbldepartflight1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(lbldepartflightcode1)
                .addGap(27, 27, 27)
                .addComponent(lbldepartdate1)
                .addGap(26, 26, 26)
                .addComponent(lbldeparttime1)
                .addGap(18, 18, 18)
                .addComponent(lbldepartfare1)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbsalutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfirst)
                            .addComponent(txtlast)
                            .addComponent(txtcontact, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(lbltotalfare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(buttonconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnjpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(departjpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(450, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(cmbsalutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtfirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(txtlast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(returnjpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltotalfare)
                    .addComponent(buttonconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(246, 246, 246)
                    .addComponent(departjpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(133, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonconfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonconfirmActionPerformed

    private void txtfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstActionPerformed

    private void buttonconfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonconfirmMouseClicked
        int x=0;
        DbAccount dba2=new DbAccount();
        if (op==2){
        try {
            x=dba2.insertdata(String.valueOf(v1.get(0)), String.valueOf(v1.get(1)), String.valueOf(v1.get(3)), String.valueOf(v1.get(5)), totalfare, String.valueOf(cmbsalutation.getSelectedItem()), txtfirst.getText(), txtlast.getText(), txtcontact.getText());
            
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FinalBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FinalBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            try {
                x=dba2.insertdata(String.valueOf(v1.get(0)), String.valueOf(v1.get(1)), String.valueOf(v1.get(3)), "N/A", totalfare, String.valueOf(cmbsalutation.getSelectedItem()), txtfirst.getText(), txtlast.getText(), txtcontact.getText());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FinalBooking.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FinalBooking.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        dispose();
        MainMenuScreen z=new MainMenuScreen();
        if (x!=0){
            JOptionPane.showMessageDialog(null, "Booking Completed!!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Error Occured!!");
        }
    }//GEN-LAST:event_buttonconfirmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalBooking().setVisible(true);
            }
        });
    }

    void flightdetails(Vector v, int option) throws SQLException {
        String code,code1,departtime=null,departfare=null,returntime = null,returnfare = null;
        op=option;
        v1=v;
        code=String.valueOf(v.get(3));
        
        DbAccount dba=new DbAccount();
        try {
            rs=dba.finaldepart(code);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FinalBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        rs.beforeFirst();
        while(rs.next()==true){
            departtime=rs.getString("departtime");
            departfare=rs.getString("fare");
        }
        
        lbldepartflight1.setText(String.valueOf(v.get(0))+" TO "+String.valueOf(v.get(1)));
        lbldepartflightcode1.setText(lbldepartflightcode1.getText()+" "+code);
        DateFormat df=new SimpleDateFormat("dd-MM-yyyy");
        
        lbldepartdate1.setText(lbldepartdate1.getText()+" "+String.valueOf(df.format(v.get(2))));
        lbldeparttime1.setText(lbldeparttime1.getText()+" "+departtime);
        lbldepartfare1.setText(lbldepartfare1.getText()+" "+departfare);
        
        totalfare+=(1.05*Integer.parseInt(departfare));
        
        if (op==2){
            returnjpanel.setVisible(true);
            code1=String.valueOf(v.get(5));
            
            DbAccount dba1=new DbAccount();
            try {
                rs=dba1.finalreturn(code1);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FinalBooking.class.getName()).log(Level.SEVERE, null, ex);
            }
            rs.beforeFirst();
        while(rs.next()==true){
            returntime=rs.getString("departtime");
            returnfare=rs.getString("fare");
        }
        
        lblreturnflight.setText(String.valueOf(v.get(1))+" TO "+String.valueOf(v.get(0)));
        lblreturnflightcode.setText(lblreturnflightcode.getText()+" "+code1);
        DateFormat df1=new SimpleDateFormat("dd-MM-yyyy");
        
        lblreturndate.setText(lblreturndate.getText()+" "+String.valueOf(df1.format(v.get(4))));
        lblreturntime.setText(lblreturntime.getText()+" "+returntime);
        lblreturnfare.setText(lblreturnfare.getText()+" "+returnfare);
        
        totalfare+=(1.05*Integer.parseInt(returnfare));
            
        }
        
        lbltotalfare.setText(lbltotalfare.getText() +" " + totalfare );

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonconfirm;
    private javax.swing.JComboBox<String> cmbsalutation;
    private javax.swing.JPanel departjpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbldepartdate1;
    private javax.swing.JLabel lbldepartfare1;
    private javax.swing.JLabel lbldepartflight1;
    private javax.swing.JLabel lbldepartflightcode1;
    private javax.swing.JLabel lbldeparttime1;
    private javax.swing.JLabel lblreturndate;
    private javax.swing.JLabel lblreturnfare;
    private javax.swing.JLabel lblreturnflight;
    private javax.swing.JLabel lblreturnflightcode;
    private javax.swing.JLabel lblreturntime;
    private javax.swing.JLabel lbltotalfare;
    private javax.swing.JPanel returnjpanel;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtfirst;
    private javax.swing.JTextField txtlast;
    // End of variables declaration//GEN-END:variables
}
