/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travel;

import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author ravisharma
 */
public class FlightBooking extends javax.swing.JFrame {

    ResultSet rs,rsreturn;
    int option;
    /**
     * Creates new form FlightBooking
     */
    public FlightBooking() throws SQLException, ClassNotFoundException {
        initComponents();
        Color backgroundcolor = new Color(0,0,0); 
        this.getContentPane().setBackground(backgroundcolor);
        departtablejpanel.setVisible(false);
        returntablejpanel.setVisible(false);
        buttonconfirm.setVisible(false);
        fillcombobox();
        setVisible(true);
        setResizable(false);
    }
    
    public void fillcombobox() throws SQLException, ClassNotFoundException{
        cmborigin.removeAllItems();
        cmbdestination.removeAllItems();
        DbAccount dba=new DbAccount();
        rs=dba.getSourceCity();
        while (rs.next()==true) cmborigin.addItem(rs.getString("source"));
        rs=dba.getDestinationCity();
        while (rs.next()==true) cmbdestination.addItem(rs.getString("destination"));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oneradio = new javax.swing.JRadioButton();
        returnradio = new javax.swing.JRadioButton();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        cmborigin = new javax.swing.JComboBox<>();
        cmbdestination = new javax.swing.JComboBox<>();
        departurejdatechooser = new com.toedter.calendar.JDateChooser();
        returnjdatechooser = new com.toedter.calendar.JDateChooser();
        buttonsearch = new javax.swing.JButton();
        buttoncancel = new javax.swing.JButton();
        buttonconfirm = new javax.swing.JButton();
        returntablejpanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbselectreturnflight = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        returntable = new javax.swing.JTable();
        departtablejpanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbselectdepartflight = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        departuretable = new javax.swing.JTable();
        lbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        oneradio.setForeground(new java.awt.Color(255, 255, 255));
        oneradio.setText("One Way");
        oneradio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneradioMouseClicked(evt);
            }
        });

        returnradio.setForeground(new java.awt.Color(255, 255, 255));
        returnradio.setText("Return");
        returnradio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnradioMouseClicked(evt);
            }
        });

        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("City of Origin");

        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setText("Destination");

        lbl4.setForeground(new java.awt.Color(255, 255, 255));
        lbl4.setText("Departure Date");

        lbl5.setForeground(new java.awt.Color(255, 255, 255));
        lbl5.setText("Return Date");

        cmborigin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbdestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbdestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdestinationActionPerformed(evt);
            }
        });

        buttonsearch.setText("Search");
        buttonsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsearchMouseClicked(evt);
            }
        });
        buttonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsearchActionPerformed(evt);
            }
        });

        buttoncancel.setText("Cancel");
        buttoncancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttoncancelMouseClicked(evt);
            }
        });

        buttonconfirm.setText("Confirm Booking");
        buttonconfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonconfirmMouseClicked(evt);
            }
        });

        jLabel5.setText("Return Flight");

        jLabel7.setText("Select your return flight");

        cmbselectreturnflight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        returntable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight id", "Airline", "Source", "Destination", "Departure", "Arrival Time", "Fare"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(returntable);

        javax.swing.GroupLayout returntablejpanelLayout = new javax.swing.GroupLayout(returntablejpanel);
        returntablejpanel.setLayout(returntablejpanelLayout);
        returntablejpanelLayout.setHorizontalGroup(
            returntablejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returntablejpanelLayout.createSequentialGroup()
                .addGroup(returntablejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, returntablejpanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(returntablejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returntablejpanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)))
                    .addGroup(returntablejpanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cmbselectreturnflight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        returntablejpanelLayout.setVerticalGroup(
            returntablejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returntablejpanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(returntablejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbselectreturnflight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jLabel6.setText("Departure Flight");

        jLabel8.setText("Select your flight");

        cmbselectdepartflight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        departuretable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight id", "Airline", "Source", "Destination", "Departure", "Arrival Time", "Fare"
            }
        ));
        jScrollPane2.setViewportView(departuretable);

        javax.swing.GroupLayout departtablejpanelLayout = new javax.swing.GroupLayout(departtablejpanel);
        departtablejpanel.setLayout(departtablejpanelLayout);
        departtablejpanelLayout.setHorizontalGroup(
            departtablejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, departtablejpanelLayout.createSequentialGroup()
                .addGroup(departtablejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, departtablejpanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(departtablejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(departtablejpanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)))
                    .addGroup(departtablejpanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cmbselectdepartflight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        departtablejpanelLayout.setVerticalGroup(
            departtablejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departtablejpanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(departtablejpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbselectdepartflight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        lbl1.setForeground(new java.awt.Color(255, 0, 0));
        lbl1.setText("HELP US TO CHOOSE THE BEST FLIGHT FOR YOU....");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttoncancel, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(buttonsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(departtablejpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returntablejpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oneradio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(returnradio))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl5)
                                    .addComponent(lbl2)
                                    .addComponent(lbl4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmborigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbdestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(returnjdatechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(departurejdatechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 646, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(buttonconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbl1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oneradio)
                            .addComponent(returnradio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl2)
                            .addComponent(cmborigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbdestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(departurejdatechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl5)
                            .addComponent(returnjdatechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addComponent(buttonsearch)
                        .addGap(45, 45, 45)
                        .addComponent(buttoncancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(departtablejpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(returntablejpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(buttonconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonsearchActionPerformed

    private void cmbdestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbdestinationActionPerformed

    private void oneradioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneradioMouseClicked
        returnradio.setEnabled(false);
        cmborigin.setEnabled(true);
        cmbdestination.setEnabled(true);
        departurejdatechooser.setEnabled(true);
        buttonsearch.setEnabled(true);
        buttoncancel.setEnabled(true);
        option=1;
        
        Date d = new Date();
        departurejdatechooser.setDate(d);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_oneradioMouseClicked

    private void returnradioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnradioMouseClicked
        oneradio.setEnabled(false);
        cmborigin.setEnabled(true);
        cmbdestination.setEnabled(true);
        departurejdatechooser.setEnabled(true);
        returnjdatechooser.setEnabled(true);
        buttonsearch.setEnabled(true);
        buttoncancel.setEnabled(true);
        option=2;
        Date d=new Date();
        departurejdatechooser.setDate(d);
        returnjdatechooser.setDate(d);
        // TODO add your handling code here:
    }//GEN-LAST:event_returnradioMouseClicked

    private void buttonsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsearchMouseClicked
        String source,dest;
        ResultSet rs1=null,rs2=null;
        if (option==1){
            source=cmborigin.getSelectedItem().toString();
            dest=cmbdestination.getSelectedItem().toString();
            DbAccount dba=new DbAccount();
            try {
                rs=dba.getDepartureFlight(source, dest);
                rs1=rs;
            } catch (SQLException ex) {
                Logger.getLogger(FlightBooking.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FlightBooking.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            departtablejpanel.setVisible(true);
            buttonconfirm.setVisible(true);
            
            TableModel tmodel=new DefaultTableModel();
            departuretable.setModel(DbUtils.resultSetToTableModel(rs));
            
            try {
                rs1.beforeFirst();
                cmbselectdepartflight.removeAllItems();
                while(rs.next()==true){
                    cmbselectdepartflight.addItem(rs1.getString("flightid"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(FlightBooking.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        else{
            source=cmborigin.getSelectedItem().toString();
            dest=cmbdestination.getSelectedItem().toString();
            DbAccount dba=new DbAccount();
            
            try {
                rs=dba.getDepartureFlight(source, dest);
                rsreturn=dba.getReturnFlight(source, dest);
                rs1=rs;
                rs2=rsreturn;
            } catch (SQLException ex) {
                Logger.getLogger(FlightBooking.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FlightBooking.class.getName()).log(Level.SEVERE, null, ex);
            }
            departtablejpanel.setVisible(true);
            returntablejpanel.setVisible(true);
            buttonconfirm.setVisible(true);
            TableModel tmodel = new DefaultTableModel(); 
            departuretable.setModel(DbUtils.resultSetToTableModel(rs)); 
            returntable.setModel(DbUtils.resultSetToTableModel(rsreturn));
            try {
                rs1.beforeFirst();
                cmbselectdepartflight.removeAllItems();
                while(rs1.next()==true){
                    cmbselectdepartflight.addItem(rs1.getString("flightid"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(FlightBooking.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                rs2.beforeFirst();
                cmbselectreturnflight.removeAllItems();
                while(rs2.next()==true){
                    cmbselectreturnflight.addItem(rs2.getString("flightid"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(FlightBooking.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonsearchMouseClicked

    private void buttoncancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttoncancelMouseClicked
        MainMenuScreen m=new MainMenuScreen();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttoncancelMouseClicked

    private void buttonconfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonconfirmMouseClicked
        Vector bookingdetails=new Vector();
        bookingdetails.addElement(cmborigin.getSelectedItem());
        bookingdetails.addElement(cmbdestination.getSelectedItem());
        bookingdetails.addElement(departurejdatechooser.getDate());
        bookingdetails.addElement(cmbselectdepartflight.getSelectedItem());
        
        if (option==2){
            bookingdetails.addElement(returnjdatechooser.getDate());
            bookingdetails.addElement(cmbselectreturnflight.getSelectedItem());
        }
        
        FinalBooking fb=new FinalBooking();
        
        try {
            fb.flightdetails(bookingdetails,option);
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(FlightBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_buttonconfirmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    try {
                        new FlightBooking().setVisible(true);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(FlightBooking.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(FlightBooking.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncancel;
    private javax.swing.JButton buttonconfirm;
    private javax.swing.JButton buttonsearch;
    private javax.swing.JComboBox<String> cmbdestination;
    private javax.swing.JComboBox<String> cmborigin;
    private javax.swing.JComboBox<String> cmbselectdepartflight;
    private javax.swing.JComboBox<String> cmbselectreturnflight;
    private javax.swing.JPanel departtablejpanel;
    private com.toedter.calendar.JDateChooser departurejdatechooser;
    private javax.swing.JTable departuretable;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JRadioButton oneradio;
    private com.toedter.calendar.JDateChooser returnjdatechooser;
    private javax.swing.JRadioButton returnradio;
    private javax.swing.JTable returntable;
    private javax.swing.JPanel returntablejpanel;
    // End of variables declaration//GEN-END:variables
}
